version: "3"

services:
  postgres-dev:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "sabrina13"
    ports:
      - "5432:5432"
    volumes:
      - /Users/alexandre/workspace/bancos/postgres:/var/lib/postgresql/data
    networks:
      - postgres-compose-network

  pgadmin-dev:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "alexandrecunha@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "sabrina13"
    ports:
      - "16543:80"
    depends_on:
      - postgres-dev
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge
